// DECK MEANS A QUEUE WITH RESTRICTIONS THAT ALLOW USER TO PERFORM INSERTION AND DELETIONS IN A SYSTEMATIC MANNER
// IN THIS TYPE OF QUEUE INSERTION OR DELETION CAN ONLY PERFORM AT THE END FRONT OR HEAD NOT DELETIOIN OR INSERTION CAN BE MADE IN MIDDLE OF THE CIRCULAR ARRAY OR CIRCULAR DOUBLY LINKED LIST
// IMPLEMENTATION OF THE DECK QUEUE USING ARRAY 

// C++ LIBRARY FILES THAT INCLUDED IN THE PROGRAM 
#include  <iostream>
#include <limits.h>
#include "deck_queue.h" // INCLUDE CLASS DEFINITION FILE 
// MAIN FUNCTION OF THE PROGRAM 
// IT'S HAVE TWO ARGUMENTS ARGC, ARGV as double array
int main (int argc, char * argv[]) {
  // CLASS INSTANTIATION 
  DeckQueue obj; // CLASS OBJECT CREATION
  return 0;
}

